name: ryu-cho

on:
  schedule:
    - cron: '0 6 * * MON'
  workflow_dispatch:

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          # ↓ personal access token (classic) with `public_repo` scope
          access-token: ${{ secrets.RYU_CHO_ACCESS_TOKEN }}
          username: ${{ secrets.RYU_CHO_USER_NAME }}
          email: ${{ secrets.RYU_CHO_USER_EMAIL }}
          upstream-repo: https://github.com/vuejs-translations/docs-cs.git
          upstream-repo-branch: upstream
          head-repo: https://github.com/vuejs/docs
          head-repo-branch: main
          track-from: d3e6c66b208ce9c806caddc83df5758d4cf55e9a
          workflow-name: ryu-cho
